### PR TITLE
Copy goss binaries to remote host 

### PR DESCRIPTION
**Pull request by SamuelMwangiW**
Kindly review this PR for a possible fix to #54

### CODE REVIEW

**Comment by SamuelMwangiW** [comment]
Default behavior is preserved. To download goss binaries locally to the Ansible control host, you may follow the official method or run:
`ansible-pull -U https://github.com/naftulikay/ansible-role-degoss/`
Sample playbook where `goss_binary_dir` is the local directory that has the `dgoss` and `goss` binaries:
```YAML
---
- hosts: all
  become: yes
  
  vars:
    goss_copy_host_binaries: true
    goss_binary_dir: /usr/local/bin/

  roles:
    - role: ansible-role-degoss
      goss_file: goss.yml

**Comment by SamuelMwangiW** [comment]
For some reason, TravisCI did not submit status but build was successful https://travis-ci.org/github/naftulikay/ansible-role-degoss/builds/736393420

**Comment by naftulikay** [comment]
Thanks for your contribution @SamuelMwangiW. I'll reply with design guidance on the source issue (#54).

**Comment by SamuelMwangiW** [comment]
> Thanks for your contribution @SamuelMwangiW. I'll reply with design guidance on the source issue (#54).

Cool

**Pull request closed without merging**
