### PR TITLE
Refactor to Support Ansible 2.3/2.4+

### PR DESCRIPTION
**Pull request by naftulikay**

### CODE REVIEW

**Review by slavaaaaaaaaaa — APPROVED** [review]
I have no idea what this does or whether it'll fix the issue but I'll put in the green tick mark

**Comment by naftulikay** [comment]
Turns out I need to distinguish between Python 2 and 3 as well :man_facepalming:

**Review by slavaaaaaaaaaa — CHANGES_REQUESTED** [review]
Sounds like you need to distinguish between python 2 and 3

**Review by slavaaaaaaaaaa — APPROVED** [review]
I don't know what to make of this anymore. Looks fixed, surely.

**Pull request merged**
